name: CodeCov

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CICD
    name: Tests
    steps:
    - uses: actions/checkout@v1
    - name: Install Symmer
      run: python3 -m pip install symmer
    - name: Install Package
      run: python3 -m pip install .
    - name: Run Tests and Collect Report
      run: python3 -m pytest --cov ./tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: cgustin99/OpenParticle
